# Numpy

In [1]:
import numpy as np

In [3]:
np.arange(0,15) #girilen aralıkta liste oluşturur

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
#burda bir de step size ekledik, bu aralıkta sayıların kaçar kaçar ilerlemesi gerektiğini belirtir
np.arange(0,27,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [5]:
np.zeros(5) #içinde 5 tane 0 olan dizi oluşturuyor

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,3)) #3*3'lük matris oluşturur sıfırlardan oluşan

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((4,4)) #4*4'lük matris oluşturur birlerden oluşan

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace method

In [8]:
np.linspace(0,20,5) #burda stop index 20'dir, 19 değil

array([ 0.,  5., 10., 15., 20.])

In [9]:
np.linspace(0,20,6) #bu aralıkta eşit farkla 6 aralık oluştur anlamında

array([ 0.,  4.,  8., 12., 16., 20.])

In [10]:
np.linspace(0,10,20) #tüm sayılar arasındaki farklar eşit,burda stop index 10'dur

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### random

In [12]:
np.random.randn(4) #rastgele 4 sayıdan oluşan array oluşturur

array([ 1.29019738, -0.76187828,  0.58758679,  0.5923848 ])

In [13]:
np.random.randn(4,4) #rastgele sayılardan oluşan 4*4'lük matrix oluşturur

array([[ 1.29457734, -1.19023542, -0.30233839,  0.34338799],
       [-0.39463215,  0.58395041,  1.73577984,  0.2342302 ],
       [-1.01193889,  0.65076515, -0.17319211, -0.8825229 ],
       [-1.0049647 , -0.64353408, -0.72581357,  1.60834524]])

In [14]:
np.random.randint(1,10) #1 ile 10 arasında random bir sayı üret(integer)

9

In [15]:
np.random.randint(1,10,5) #1 ile 10 arasında(10 dahil değil) random 5 sayı üret

array([2, 1, 3, 5, 5])

### Numpy array methods

In [16]:
nparray = np.arange(30)

In [17]:
nparray.reshape(5,6) #bu diziyi 5*6'lık matrise çevirir

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
nparray = nparray.reshape(6,5) #bu diziyi 6*5'lik matrise çevirir
#burda reshape(7*5) deseydik hata verirdi çünkü 7*5'lik matriste 35 eleman olmalıdır

In [30]:
nparray.max() #dizi içindeki en büyük değeri döndürür

29

In [31]:
nparray.min() #dizi içindeki en küçük değeri döndürür

0

In [22]:
randarray = np.random.randint(0,97,35)

In [23]:
randarray

array([40,  9,  8, 35, 34, 89, 21, 13, 38, 40, 25, 46, 64, 72, 45, 14, 96,
       55, 50, 44,  4, 80, 46, 68, 93, 28, 36, 40, 76, 90, 96, 67, 73, 71,
       63])

In [24]:
randarray.argmax() #en büyük elemanın hangi indekste old. bilgisini verir

16

In [25]:
randarray.argmin() #en küçük elemanın hangi indekste old. bilgisini verir

20

In [26]:
randarray.shape #bu bir attribute'dur, boyut bilgisini verir

(35,)

In [29]:
nparray.shape

(6, 5)

### Indexing

In [2]:
myarray = np.arange(0,15)
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
myarray[6] #myarray dizisinin 6.indeksinde bulunan elemanı döndür

6

In [4]:
myarray[3:8] #slicing

array([3, 4, 5, 6, 7])

In [5]:
myarray[4:9] = -3 #bu aralıktaki indekslere yeni değer atadık

In [6]:
myarray

array([ 0,  1,  2,  3, -3, -3, -3, -3, -3,  9, 10, 11, 12, 13, 14])

In [7]:
arr1 = np.random.randint(0,90,37)

In [8]:
arr1

array([81, 35, 21, 54, 27, 78, 72, 83, 87, 17, 84, 47, 87, 87, 72, 86, 68,
       34, 38, 52, 16,  8, 62, 27,  8, 32, 25,  8, 50, 18, 10, 48, 62, 54,
       61, 52,  4])

In [10]:
slicingarr = arr1[4:28]
slicingarr

array([27, 78, 72, 83, 87, 17, 84, 47, 87, 87, 72, 86, 68, 34, 38, 52, 16,
        8, 62, 27,  8, 32, 25,  8])

In [11]:
slicingarr[:] #indeksleme yaparken hepsini alır 

array([27, 78, 72, 83, 87, 17, 84, 47, 87, 87, 72, 86, 68, 34, 38, 52, 16,
        8, 62, 27,  8, 32, 25,  8])

In [12]:
slicingarr[:] = 250 #tüm elemanlarını 250'ye eşitler

In [13]:
slicingarr

array([250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250,
       250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250])

In [14]:
arr1

array([ 81,  35,  21,  54, 250, 250, 250, 250, 250, 250, 250, 250, 250,
       250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250,
       250, 250,  50,  18,  10,  48,  62,  54,  61,  52,   4])

#### Elimizdeki veri seti(türü her ne ise) üzerinde işlemler yapalım ama orijinal hali değişmesin istiyorsak copy() metodunu kullanırız ve veri setinin aslını korumuş oluruz.

In [15]:
arr1copy = arr1.copy()

In [17]:
arr1copy

array([ 81,  35,  21,  54, 250, 250, 250, 250, 250, 250, 250, 250, 250,
       250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250,
       250, 250,  50,  18,  10,  48,  62,  54,  61,  52,   4])

### Matrix 

In [18]:
mymatrix = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [19]:
mymatrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
mymatrix[0] #0.indekste bulunan satırı veriyor

array([10, 20, 30])

In [22]:
mymatrix[1][2] #1.satır 2.sütündaki eleman 

60

In [23]:
mymatrix[1,2] #bu da aynı sonucu verir, numpy'da aynı işlemi yaparlar

60

In [24]:
mymatrix[2:,2:]

array([[90]])

In [25]:
#içine liste olarak da verebiliriz
mymatrix[[0,2]] #0 ve 2.indekstekileri döndürür

array([[10, 20, 30],
       [70, 80, 90]])

In [26]:
arr2 = np.random.randint(0,99,25)
arr2

array([12, 79,  2, 94, 66, 13, 94, 87, 31, 79, 64, 22, 96, 87, 74, 71, 80,
       54, 90, 94, 52, 48, 18, 82, 73])

In [27]:
arr2[arr2 > 24] #arr2 dizisindeki 24'ten büyük elemanları verir

array([79, 94, 66, 94, 87, 31, 79, 64, 96, 87, 74, 71, 80, 54, 90, 94, 52,
       48, 82, 73])

In [28]:
arr2 + arr2

array([ 24, 158,   4, 188, 132,  26, 188, 174,  62, 158, 128,  44, 192,
       174, 148, 142, 160, 108, 180, 188, 104,  96,  36, 164, 146])

In [29]:
arr2 * arr2

array([ 144, 6241,    4, 8836, 4356,  169, 8836, 7569,  961, 6241, 4096,
        484, 9216, 7569, 5476, 5041, 6400, 2916, 8100, 8836, 2704, 2304,
        324, 6724, 5329])